### ISSUE TITLE
Chrome Notifications and Google Hangouts

### ISSUE THREAD

**Issue by jodyalbritton** [rgcjonas/gnome-shell-extension-appindicator#43]
Extension: v14
Shell: 3.12.2
Kernel: Linux jody-desktop 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Distribution: Ubuntu 14.04.1 LTS
Loaded Indicators: software-update-available chrome_app_indicator_1 chrome_app_indicator_2

Missing icons for Chrome Notifications and Google Hangouts. I can see the highlight where the icons should be, but the icons are not visible.

**Comment by nealmcb** [comment]
I have this issue also.  I just switched to gnome-shell 3.10.4-0ubuntu5.2 from Unity on Ubuntu 14.04 Trusty.  I'm using Chrome (version 47.0.2526.16 beta (64-bit)), and don't see the hangouts indicator I used to have in my top panel in Unity.  I don't see a bottom notification tray at all in gnome-shell, and I'd prefer to not lose real estate by installing one.
How can I get to hangouts without going to a chrome window (to find the hangout extension in its upper right extensions area)?   Thanks!

**Comment by rgcjonas** [comment]
No new development will happen for Gnome Shell 3.10. 

Besides, Chrome [doesn't even attempt to use the KSNI protocol unless it is running under KDE or Unity](https://chromium.googlesource.com/chromium/src.git/+/master/chrome/browser/ui/libgtk2ui/app_indicator_icon.cc#90). There's nothing we can do about it. Go complain upstream.
