### ISSUE TITLE
Outdated version on extensions.gnome.org

### ISSUE THREAD

**Issue by mavit** [rgcjonas/gnome-shell-extension-appindicator#49]
Page https://extensions.gnome.org/extension/615/appindicator-support/ says that AppIndicator Support is "outdated".  It will not install on Gnome 3.14 on Fedora 21.

It looks like this has been fixed in git, so it should just be a case of pushing a new release?

**Comment by cnlpete** [comment]
:+1:

**Comment by edubxb** [comment]
+1

**Comment by rgcjonas** [comment]
The new v15 release has just been uploaded to extensions.gnome.org and is expected to be approved in the following days.

**Comment by edubxb** [comment]
Thanks!
