### ISSUE TITLE
long indicator menus don't fit into the screen

### ISSUE THREAD

**Issue by cyberalex4life** [rgcjonas/gnome-shell-extension-appindicator#50]
I don't know if this is what your extension do, because there are problems with virtually any extended menu that doesn't fit into the screen, not only indicators.
There is a right click menu, and I think this should happen to all windows that don't fit the size of the screen. Probably it should be a separate extension. Don't know if it's already implemented in newer versions of gnome shell. I am using Ubuntu Gnome Trusty amd64 with GS 3.10.

![menu_015](https://cloud.githubusercontent.com/assets/2423189/6166523/939cc4e0-b2b9-11e4-93ca-15efdc87890f.jpg)

Anyway sorry bugging you, I had this on my mind for some time.

**Comment by rgcjonas** [comment]
Even if a workaround were possible, I won't code it. 

This ultimately needs to be fixed upstream in GNOME Shell. They have been ignoring Menu issues for the past years, so don't get your hopes up.
