### ISSUE TITLE
syncthing indicator

### ISSUE THREAD

**Issue by cedricbrx** [rgcjonas/gnome-shell-extension-appindicator#51]
Hi,

I'm usign syncthing-gtk, which is using python and libappindicator, but appindicator-support does not find the indicator and it remains in the message tray

**Comment by rgcjonas** [comment]
syncthing-gtk (at least v0.7.5.1 which I tested) needs to be started with the environment variable `SYNCTHING_STATUS_BACKEND=AppIndicator`; otherwise it will use a standard systray icon.

You need to bring this up with the syncthing-gtk developers.
