### ISSUE TITLE
g_variant_compare() is used on GVariant of type 'ay'

### ISSUE THREAD

**Issue by lestcape** [rgcjonas/gnome-shell-extension-appindicator#53]
As you say, possible the crash will be the png icons. I see that is possible send a icon-data

https://github.com/rgcjonas/gnome-shell-extension-appindicator/blob/9dcf3fcf1e948823c10d1712505cba14c95fdb4d/dbusMenu.js#L79

then, here https://github.com/rgcjonas/gnome-shell-extension-appindicator/blob/9dcf3fcf1e948823c10d1712505cba14c95fdb4d/dbusMenu.js#L132

there are a comparation of a type "ay" and a GVariant comparation is only for basic types: https://developer.gnome.org/glib/stable/glib-GVariant.html#g-variant-compare 

 Is know that this types of comparations could cause problems...

Another situation will be that you have here some flags to prevent lost data on the layout:
https://github.com/rgcjonas/gnome-shell-extension-appindicator/blob/9dcf3fcf1e948823c10d1712505cba14c95fdb4d/dbusMenu.js#L223

Will not be also important for properties?

I test for some time how the update of items occurs and normally they update several things at the same time and then could delayed for a long time without any other update. So, will not be usefull send the update of layout and properties to an idle, waiting for all Dbus changes and then update only one time the layout or properties?

Regards.

**Comment by rgcjonas** [comment]
The `g_variant_compare` thing is a bug, and may indeed impact icon updates.

If you think you found an issue with how property updates are handled, please write a test case to demonstrate the issue.

**Comment by lestcape** [comment]
In any case, i think what happen is that always will update the icons, also if is not needed(as the comparation return false). So, will impact the performance, not more.
