### ISSUE TITLE
Gnome 3.16 support

### ISSUE THREAD

**Issue by 183amir** [rgcjonas/gnome-shell-extension-appindicator#54]
Please add Gnome 3.16 support.

**Comment by 183amir** [comment]
Please add Gnome 3.16 support.

**Comment by cyberalex4life** [comment]
From what I have seen here https://extensions.gnome.org/extension/615/appindicator-support/
you only have to add 3.16 to metadata.json.

**Comment by 183amir** [comment]
Probably. I did that already and it's working but it would be great if you could add it in upstream too. 
I'll report back if I face some problems.

**Comment by cyberalex4life** [comment]
I'm just a frequent user, not a/the mantainer....
