### ISSUE TITLE
This extension makes the shell very unstable during GNotification events (Corebird)?

### ISSUE THREAD

**Issue by axfelix** [rgcjonas/gnome-shell-extension-appindicator#59]
I originally opened this bug on Corebird, but the author seemed stumped other than suggesting it might be GNotification-related; wonder if you can duplicate and/or have any ideas what could be going on. Corebird notifications crash the shell about once time in five when using this extension; never happens otherwise.

https://github.com/baedert/corebird/issues/405

**Comment by rgcjonas** [comment]
Crashing the shell is entirely possible, we did that on a regular basis back in 2013. I thought we (and the gjs folks) got our shit together in early 2014, but apparently not. However, debugging shell crashes can be funny from time to time, so maybe I can afford to spend some time trying to fix it.

I do not use twitter, so Corebird is pretty useless for me. Could you provide me with any logs, backtraces, core dumps or a minimal program to reproduce the issue, something like a little python script spamming the shell with notifications? Which versions of the Shell and the extension are affected? How reliably can this be reproduced?

**Comment by axfelix** [comment]
Here's some output from systemctl:

Oct 28 15:18:55 nixon gnome-session[1791]: Gjs-Message: JS LOG: loading user theme: /usr/share//themes/Numix-Frost-Light/gnome-shell/gnome-shell.css
Oct 28 15:18:55 nixon gnome-session[1791]: Gjs-Message: JS LOG: loading user theme: /usr/share//themes/Numix-Frost-Light/gnome-shell/gnome-shell.css
Oct 28 15:18:55 nixon gnome-session[1791]: Gjs-Message: JS WARNING: [/home/axfelix/.local/share/gnome-shell/extensions/chatstatus@zeten30.gmail.com/extension.js 116]: variable label redeclares argument
Oct 28 15:18:55 nixon gnome-session[1791]: Gjs-Message: JS LOG: [AppIndicatorSupport-DEBUG] Reload detected, destroying old watchdog
Oct 28 15:18:56 nixon gnome-session[1791]: Gjs-Message: JS LOG: loading user theme: /usr/share//themes/Numix-Frost-Light/gnome-shell/gnome-shell.css
Oct 28 15:18:56 nixon gnome-session[1791]: Gjs-Message: JS WARNING: [/home/axfelix/.local/share/gnome-shell/extensions/chatstatus@zeten30.gmail.com/extension.js 116]: variable label redeclares argument
Oct 28 15:18:56 nixon gnome-session[1791]: Gjs-Message: JS LOG: [AppIndicatorSupport-DEBUG] Reload detected, destroying old watchdog
Oct 28 15:18:57 nixon everpad.desktop[9160]: "sni-qt/9160" WARN  15:18:57.361 void StatusNotifierItemFactory::connectToSnw() IsStatusNotifierHostRegistered returned something which is not a bool: QVariant(, )
Oct 28 15:18:57 nixon gnome-session[1791]: Gjs-Message: JS LOG: [AppIndicatorSupport-WARN] Failed to acquire org.kde.StatusNotifierWatcher
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Oct 28 15:18:57 nixon steam.desktop[6873]: (steam:6970): libappindicator-WARNING **: Unable to connect to the Notification Watcher: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.kde.StatusNotifierWatcher' on o
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failednticationAgent, locale en_CA.utf8) (disconnected from bus)
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed_update_capabilities: assertion 'TP_IS_CONNECTION (proxy)' failed
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed_update_capabilities: assertion 'TP_IS_CONNECTION (proxy)' failed
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's parent.
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has already a parent of type 'ShellGenericContainer'.
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's parent.
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has already a parent of type 'ShellGenericContainer'.
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's parent.
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has already a parent of type 'ShellGenericContainer'.
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's parent.
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has already a parent of type 'ShellGenericContainer'.
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's parent.
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has already a parent of type 'ShellGenericContainer'.
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's parent.
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has already a parent of type 'ShellGenericContainer'.
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's parent.
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has already a parent of type 'ShellGenericContainer'.
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): GLib-GObject-WARNING **: gsignal.c:2634: instance '0x23f3be0' has no handler with id '48699'_update_capabilities: assertion 'TP_IS_CONNECTION (proxy)' failed
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): GLib-GObject-WARNING **: gsignal.c:2634: instance '0x23f3be0' has no handler with id '48699'_update_capabilities: assertion 'TP_IS_CONNECTION (proxy)' failed
Oct 28 15:18:57 nixon gnome-session[1791]: (gnome-shell:7693): GLib-GObject-WARNING **: gsignal.c:2634: instance '0x23f3be0' has no handler with id '48699'_update_capabilities: assertion 'TP_IS_CONNECTION (proxy)' failed
Oct 28 15:18:57 nixon gnome-session[1791]: **_update_capabilities: assertion 'TP_IS_CONNECTION (proxy)' failed
Oct 28 15:18:57 nixon gnome-session[1791]: St:ERROR:st/st-bin.c:185:st_bin_dispose: assertion failed: (priv->child == NULL)_update_capabilities: assertion 'TP_IS_CONNECTION (proxy)' failed
Oct 28 15:18:58 nixon polkitd[299]: Unregistered Authentication Agent for unix-session:c2 (system bus name :1.396, object path /org/freedesktop/PolicyKit1/Authe_update_capabilities: assertion 'TP_IS_CONNECTION (proxy)' failed
Oct 28 15:18:58 nixon org.freedesktop.Telepathy.AccountManager[1838]: (process:2004): tp-glib-CRITICAL **: tp_cli_connection_interface_contact_capabilities_call_update_capabilities: assertion 'TP_IS_CONNECTION (proxy)' failed
Oct 28 15:18:58 nixon org.freedesktop.Telepathy.AccountManager[1838]: (process:2004): tp-glib-CRITICAL **: tp_cli_connection_interface_contact_capabilities_call_update_capabilities: assertion 'TP_IS_CONNECTION (proxy)' failed
Oct 28 15:18:58 nixon org.freedesktop.Telepathy.AccountManager[1838]: (process:2004): tp-glib-CRITICAL **: tp_cli_connection_interface_contact_capabilities_call_update_capabilities: assertion 'TP_IS_CONNECTION (proxy)' failed
Oct 28 15:18:58 nixon org.freedesktop.Telepathy.AccountManager[1838]: (process:2004): tp-glib-CRITICAL **: tp_cli_connection_interface_contact_capabilities_call
Oct 28 15:18:58 nixon org.freedesktop.Telepathy.AccountManager[1838]: (process:2004): tp-glib-CRITICAL **: tp_cli_connection_interface_contact_capabilities_call
Oct 28 15:18:58 nixon org.freedesktop.Telepathy.AccountManager[1838]: (process:2004): tp-glib-CRITICAL **: tp_cli_connection_interface_contact_capabilities_call
Oct 28 15:18:58 nixon org.freedesktop.Telepathy.AccountManager[1838]: (process:2004): tp-glib-CRITICAL **: tp_cli_connection_interface_contact_capabilities_call
Oct 28 15:18:58 nixon org.freedesktop.Telepathy.AccountManager[1838]: (process:2004): tp-glib-CRITICAL **: tp_cli_connection_interface_contact_capabilities_call
Oct 28 15:18:58 nixon org.freedesktop.Telepathy.AccountManager[1838]: (process:2004): tp-glib-CRITICAL **: tp_cli_connection_interface_contact_capabilities_call
Oct 28 15:18:58 nixon org.freedesktop.Telepathy.AccountManager[1838]: (process:2004): tp-glib-CRITICAL **: tp_cli_connection_interface_contact_capabilities_call
Oct 28 15:18:58 nixon org.freedesktop.Telepathy.AccountManager[1838]: (process:2004): tp-glib-CRITICAL **: tp_cli_connection_interface_contact_capabilities_call
Oct 28 15:18:58 nixon gnome-session[1791]: gnome-session-binary[1791]: WARNING: Application 'gnome-shell.desktop' killed by signal 6
Oct 28 15:18:58 nixon gnome-session-binary[1791]: WARNING: Application 'gnome-shell.desktop' killed by signal 6
Oct 28 15:18:58 nixon systemd-coredump[7880]: Process 7693 (gnome-shell) of user 1000 dumped core.

Happens about one in five times Corebird throws a notification while I have this extension enabled, like I said. Makes me glad the shell is so good at restarting itself :)

**Comment by axfelix** [comment]
Any update on this?

**Comment by jhasse** [comment]
> Any update on this?

Sorry for the long silence. Is this bug still valid?

**Comment by axfelix** [comment]
Issues are much less frequent than they were; I still have the behavior very rarely but I think this can be closed.
