### ISSUE TITLE
Not work with Gnome Shell 3.20 

### ISSUE THREAD

**Issue by ArthurGarnier** [rgcjonas/gnome-shell-extension-appindicator#62]
Appindicator is not compatible with Gnome Shell 3.20

**Comment by dannerph** [comment]
No problem here for me after adding "3.20" in metadata.json

Running Arch Linux and Gnome 3.20

Thanks to this extension Synology Cloud Station tray icons are finally showing up on my system.

**Comment by dralley** [comment]
@rgcjonas @jhasse The extensions.gnome.org site still has yet to be updated with the new version, so trying to install this addon directly without modification is broken on Fedora 24, 25, Arch... essentially every distribution that isn't using 3.18 or older. Please fix this.
