### ISSUE TITLE
MEGASync icon blue?

### ISSUE THREAD

**Issue by cra0zy** [rgcjonas/gnome-shell-extension-appindicator#66]
MEGASync icon is shown blue instead of red:

![blue](https://cloud.githubusercontent.com/assets/6773302/23261182/76d0cab8-f9d5-11e6-980d-787c951caf56.png)

**Comment by jhasse** [comment]
Btw: How do you make MEGASync not user the legacy tray? I couldn't get it to work.

**Comment by cra0zy** [comment]
I've just installed the megasync package from their website, I didn't do anything special.

**Comment by jhasse** [comment]
strange ... Which distro / GNOME shell version are you using?

**Comment by cra0zy** [comment]
Arch Linux, Gnome 3.22

**Comment by cra0zy** [comment]
`sni-qt` package on Ubuntu is needed for MEGA to use appindicator instead of the old status icon.
