### ISSUE TITLE
Ubuntu Gnome 17.04 Gnome 3.24 no indicator is shown

### ISSUE THREAD

**Issue by Feichtmeier** [rgcjonas/gnome-shell-extension-appindicator#67]
Atfer I install your extension via gnome extensions homepage no indicators show up. 
Also, wenn I reboot the extension is deactivated again on the homepage and in fact not installed. :(

**Comment by d0od88** [comment]
Same on my 17.04 install.

**Comment by ebruck** [comment]
Adding 3.24 to metadata.json's list of shell versions makes it work for me. Radiotray-NG is working just fine under Ubuntu GNOME 17.04.

"shell-version": ["3.16", "3.17.91", "3.18", "3.20", "3.22", "3.24"],

Thanks for an awesome extension!
