### ISSUE TITLE
Slack Indicator Missing

### ISSUE THREAD

**Issue by hackel** [rgcjonas/gnome-shell-extension-appindicator#70]
This extension is not showing the indicator icon from Slack's desktop application (https://slack.com/downloads/linux).  It works fine with Scudcloud, Transmission, etc.  If I enable Topicons+, it shows up fine. 

Environment:
gnome-shell-extension-appindicator v18 (also tried latest master 28d0ac8)
Ubuntu 16.10
gnome-shell 3.22.3
Slack 2.5.2 (Electron app)

**Comment by angystardust** [comment]
Same problem here with Slack but I've found an easy way to fix it:
http://www.webupd8.org/2017/04/fix-appindicator-not-working-for.html

P.s.: I solved the same problem with Pidgin by installing the pidgin-indicator package (on fedora) and enabling the plugin in the pidgin settings. @jhasse maybe we could create a wiki page (or maybe on the README.md) with all those fix/workaround. By the wat, thank you so much for this useful extension. Keep up the good work 👍

**Comment by hackel** [comment]
Thanks @angystardust that method worked.  I switched from Unity to GNOME shortly before upgrading to 17.04, so I didn't realise it was no longer working in Unity, either.

One minor quip is that the icon gets rendered considerably smaller than it does in TopIcons+, but I suppose that should be a separate issue.

**Comment by jhasse** [comment]
>  @jhasse maybe we could create a wiki page (or maybe on the README.md) with all those fix/workaround.

I think the wiki is a good place for that. Feel free to add anything here: https://github.com/rgcjonas/gnome-shell-extension-appindicator/wiki

> One minor quip is that the icon gets rendered considerably smaller than it does in TopIcons+, but I suppose that should be a separate issue.

#68

**Comment by jhasse** [comment]
We should continue the discussion in #74.
