### ISSUE TITLE
No HiDPI support

### ISSUE THREAD

**Issue by kicsyromy** [rgcjonas/gnome-shell-extension-appindicator#71]
Distribution: ArchLinux, 4.10.11-1-ARCH x86_64 unknown GNU/Linux
GNOME Shell: version 3.24.1
Extension version: latest from extensions.gnome.org
Indicators affected: all
Steps to reproduce issue: Run GNOME Shell 3.22 or above (only ones tested) on a HiDPI display.
Issue observed: The icons are very small, they don't take into account display scaling.
Additional information:
Setting `this.width` and `this.height` (lines 222,223 in `appIndicator.js`) to `icon_size * 2` works around issue. But in this case it breaks all the icons for non-HiDPI screens.
Patch [double_icon_size_patch.txt](https://github.com/rgcjonas/gnome-shell-extension-appindicator/files/952116/double_icon_size_patch.txt)
Screenshot 
![screenshot from 2017-04-24 17-44-01](https://cloud.githubusercontent.com/assets/10869778/25342758/a483c108-2915-11e7-8fd4-2f6e7a24290c.png)

**Comment by kicsyromy** [comment]
I would gladly make a pull request with a proper fix if I had some guidance.

**Comment by jhasse** [comment]
Thanks for the report :) Can you try if the following works?

```javascript
const St = imports.gi.St;

// ...

        let scale_factor = St.ThemeContext.get_for_stage(global.stage).scale_factor;
        this.width  = icon_size * scale_factor;
        this.height = icon_size * scale_factor
```

**Comment by kicsyromy** [comment]
@jhasse Sure thing, I'll give it a go once I get home, and get back to you with the results.
