### ISSUE TITLE
Icons not shown anymore

### ISSUE THREAD

**Issue by tigerjack** [rgcjonas/gnome-shell-extension-appindicator#77]
As per the title, the icons are not shown anymore. I don't think I've changed something. What can I send in order to help you?

**Comment by jhasse** [comment]
Which applications are you using?

**Comment by tigerjack** [comment]
Dropbox, Insync, Telegram and Transmission. I also had indicator-multiload which I managed to replace with a native gnome-shell extension.

**Comment by tigerjack** [comment]
After a couple of purge and restarts all icons are again there. Thanks a lot anyway.
