### ISSUE TITLE
Reduce space between icons

### ISSUE THREAD

**Issue by dylanparry** [rgcjonas/gnome-shell-extension-appindicator#78]
Hi,

First off, great extension. Thank you for creating it!

I was wondering if it's possible to decrease the amount of space between each icon? I know there isn't a settings screen, but is it possible for me to manually change the padding between icons in one of the extension `.js` files?

Thanks,

Dylan

**Comment by jhasse** [comment]
https://extensions.gnome.org/extension/355/status-area-horizontal-spacing/

**Comment by NateSwanson7** [comment]
You can manually change the space between the icons by doing the following:

1. go to extension's directory: `cd /usr/share/gnome-shell/ubuntu-appindicators@ubuntu.com`
2. edit file: `appIndicator.js`
3. find class: `class AppIndicators_IconActor`
4. within the class "constructor" `_init(indicator, icon_size)` find: `this.width  = icon_size * themeContext.scale_factor` (Line 286 as of April 26, 2019)
5. update `this.width  = icon_size * themeContext.scale_factor` to include the space you'd like between icons. I used the following: `this.width  = (icon_size * themeContext.scale_factor)+5`
6. Save the file and restart gnome-shell `Alt+F2` > `r` > `Enter`

**BEFORE**
![icons](https://user-images.githubusercontent.com/31102449/56821475-068c3f80-6814-11e9-9ac6-962a6cb12cb3.png)


**AFTER**
![icons+5](https://user-images.githubusercontent.com/31102449/56821486-1015a780-6814-11e9-875f-715bb91f6295.png)
