### ISSUE TITLE
Icon size & spacing

### ISSUE THREAD

**Issue by Hombremaledicto** [rgcjonas/gnome-shell-extension-appindicator#79]
I don't know if this extension is still in active development, but i'd like to post a feature request: allowing users to set the icon size and spacing among indicators. See the attachment, on the very left there are indicators from this extension:

![schermata del 2017-06-14 20-52-32](https://user-images.githubusercontent.com/7595097/27149319-6a6fb4da-5143-11e7-816f-bfa35a5edc41.png)

Thank you very much for your time and work by the way :+1:

**Comment by redpop1** [comment]
Indeed, for me the icons are to small

**Comment by jhasse** [comment]
Thanks for creating this issue :)

See #68 for updates about this.

**Comment by jhasse** [comment]
Regarding spacing: Check out https://extensions.gnome.org/extension/355/status-area-horizontal-spacing/
